```{r results="hide",echo=FALSE}
VERSION <- readLines("~/Projects/clustering-data-v1/VERSION")
```

(sec:data-v1)=
# Explore Datasets (v`r VERSION`)

```{python echo=FALSE,results="hide"}
import shutil, os.path
shutil.rmtree("../_static/catalogue-v1", ignore_errors=True)
shutil.copytree(
    os.path.expanduser("~/Projects/clustering-data-v1/.catalogue/"),
    "../_static/catalogue-v1",
    ignore=shutil.ignore_patterns('*.md', '*.csv')
)
```


*Select battery/dataset from the {ref}`sec:suite-v1`:*

::::{raw} html
<form style="margin-bottom: 2em">

<div style="text-align: center">
<span id="select_prev" class="btn btn-neutral float-left" title="Previous dataset"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span></span>

<select id="select_battery" name="select_battery" class="btn btn-neutral">
</select>
/
<select id="select_dataset" name="select_dataset" class="btn btn-neutral">
</select>

<span id="select_next" class="btn btn-neutral float-right" title="Next dataset"><span class="fa fa-arrow-circle-right" aria-hidden="true"></span></span>
</div>

</form>
::::


*Preview (only for 1–3 dimensional datasets):*

::::{raw} html

<div id="dataset_showcase">

</div>
::::




::::{raw} html
<script type="text/javascript">

var suite =
```{python echo=FALSE,results="asis"}
import pandas as pd
import json

batteries = [
    "wut", "sipu", "fcps", "graves", "other",
    "uci", "mnist", "g2mg", "h2mg"
]

suite = dict()
for battery in batteries:
    x = pd.read_csv(
        "~/Projects/clustering-data-v1/.catalogue/%s.csv" % battery
    )

    suite[battery] = dict()
    for dataset, labels in x.groupby("dataset", sort=False).labels:
        suite[battery][dataset] = labels.to_list()

print(json.dumps(suite))
```
;



function addToSelect(select_id, elems, selected=null) {
    let select = document.getElementById(select_id);
    while (select.lastChild) select.removeChild(select.lastChild);
    for (let battery in elems) {
        let opt = document.createElement("option");
        opt.value = opt.innerHTML = battery;
        if (selected) {
            if (battery == selected) opt.selected = true;
        }
        else {
            selected = battery;
        }
        select.appendChild(opt);
    }
    return selected;
}



let battery = location.hash.substring(1, location.hash.lastIndexOf("/"));
if (!(battery && (battery in suite))) battery = null;
battery = addToSelect("select_battery", suite, battery);

let dataset = location.hash.substring(location.hash.lastIndexOf("/")+1);
if (!(dataset && (dataset in suite[battery]))) dataset = null;
dataset = addToSelect("select_dataset", suite[battery], dataset);

location.hash = battery + "/" + dataset;


function selectNextDataset() {
    let select = document.getElementById('select_dataset');
    select.selectedIndex += 1;

    if (select.selectedIndex < 0) {
        let select2 = document.getElementById('select_battery');
        select2.selectedIndex += 1;
        if (select2.selectedIndex < 0)
            select2.selectedIndex = 0;

        let battery = select2.value;
        addToSelect("select_dataset", suite[battery]);

        select.selectedIndex = 0;
    }

    datasetChanged();
}


function selectPrevDataset() {
    let select = document.getElementById('select_dataset');
    select.selectedIndex -= 1;

    if (select.selectedIndex < 0) {
        let select2 = document.getElementById('select_battery');
        select2.selectedIndex -= 1;
        if (select2.selectedIndex < 0)
            select2.selectedIndex = select2.children.length-1;

        let battery = select2.value;
        addToSelect("select_dataset", suite[battery]);

        select.selectedIndex = select.children.length-1;
    }

    datasetChanged();
}



document.getElementById("select_prev").onclick = selectPrevDataset;
document.getElementById("select_next").onclick = selectNextDataset;



function datasetChanged() {
    let battery = document.getElementById("select_battery").value;
    let dataset = document.getElementById("select_dataset").value;
    location.hash = battery + "/" + dataset;
}


function batteryChanged() {
    let battery = document.getElementById("select_battery").value;
    addToSelect("select_dataset", suite[battery]);
    datasetChanged();
}

document.getElementById("select_dataset").onchange = datasetChanged;
document.getElementById("select_battery").onchange = batteryChanged;





function locationHashChanged()
{
//     els = document.getElementsByClassName("clustbench_browsable");
//     for (let i=0; i<els.length; i++)
//         els[i].style.display = "none";
//
//     var x = location.hash.substring(1);
//     if (x == "") return;
//     el = document.getElementById(x);
//     if (!el) return;
//     el.style.display = "block";

    var battery = location.hash.substring(1, location.hash.lastIndexOf("/"));
    var dataset = location.hash.substring(location.hash.lastIndexOf("/")+1);

    if (!((battery in suite) && (dataset in suite[battery]))) return;

    var labels = suite[battery][dataset];
    let showcase = document.getElementById("dataset_showcase");
    while (showcase.lastChild) showcase.removeChild(showcase.lastChild);

    let head = document.createElement("h2");
    head.innerHTML = battery + "/" + dataset;
    showcase.appendChild(head);

    for (let l in labels) {
//         let head = document.createElement("h3");
//         head.innerHTML = labels[l];
//         showcase.appendChild(head);

        let figure = document.createElement("figure");
        figure.class = "align-default"

        let img = document.createElement("img");
        img.title = img.alt = labels[l];
        img.src = "../_static/catalogue-v1/" + battery + "/" +
            dataset + "." + labels[l] + ".png";

        figure.appendChild(img);
        showcase.appendChild(figure);
    }


    head = document.createElement("h3");
    head.innerHTML = "Description";
    showcase.appendChild(head);

    let pre = document.createElement("pre");
    pre.id = "dataset_description";
    pre.text = "Description";
    showcase.appendChild(pre);

    let xhr = new XMLHttpRequest();
    xhr.onload = function() {
        document.getElementById("dataset_description").textContent = this.responseText;
    };
    xhr.open("GET", "../_static/catalogue-v1/" + battery + "/" +
            dataset + ".txt");
    xhr.send();
}




window.onhashchange = locationHashChanged;
locationHashChanged();
</script>
::::
