(sec:many-partitions)=
# There Can Be Many Valid Partitions

We believe that it is in the very spirit of unsupervised learning
that for some datasets, **there might be multiple equally
valid/plausible/useful partitions**
(see also {cite}`sdmc,LuxburgETAL2012:clustscienceart` for discussion).

This is why many benchmark sets in our battery come with alternative labellings.
For instance, consider the {ref}`graves/parabolic <sec:data-v1>`
dataset {cite}`graves`:

```{python}
import numpy as np
import clustbench
data_url = "https://github.com/gagolews/clustering-data-v1/raw/master"
benchmark = clustbench.load_dataset("graves", "parabolic", url=data_url)
```

It is equipped with two different reference partitions:

```{python}
len(benchmark.labels)
```

They are depicted below.


```{python many-paritions,results="hide",fig.cap="Does this dataset consist of two paraboles or four spherical blobs? There can be many equally valid partitions."}
import genieclust
for i in range(len(benchmark.labels)):
    plt.subplot(1, len(benchmark.labels), i+1)
    genieclust.plots.plot_scatter(
        benchmark.data, labels=benchmark.labels[i]-1,
        axis="equal", title=f"labels{i}"
    )

plt.show()
```

::::{note}
New new label sets can be {ref}`contributed <sec:contributing>`
by experts in the future.
See also the *{ref}`Colouriser <sec:colouriser>`* class
for a way to generate label vectors interactively (for planar datasets).
::::




.....

::::{important}
The **outputs generated by a single algorithm
should be evaluated against all the available reference labellings
and the *maximal* similarity score should be reported.
::::



```{python}
scores = []
g = genieclust.Genie()
for y_true in labels:
    k = max(y_true)
    g.set_params(n_clusters=k)
    y_pred = g.fit_predict(X) + 1  # +1 makes cluster IDs in 1..k, not 0..(k-1)
    scores.append(
        genieclust.compare_partitions.adjusted_asymmetric_accuracy(
            y_true[y_true>0],  # do not count noise points
            y_pred[y_true>0]
        )
    )
print(scores)
```

```{python}
max(scores)
```

TO DO...



