```{r results="hide",echo=FALSE}
VERSION <- readLines("~/Projects/clustering-data-v1/VERSION")
```

```{python results="hide",echo=FALSE}
import pandas as pd
import numpy as np

def summarise_battery(battery):
    x = pd.read_csv(
        "~/Projects/clustering-data-v1/.catalogue/%s.csv" % battery
    )
    x = x.iloc[:, 1:]  # skip battery
    x = x.rename(columns=dict(
        noise="noise points",
        k="*k*",
        n="*n*",
        d="*d*",
        labels="reference labels",
    ))

    idx = [""]*x.shape[0]
    j = 1
    for i in range(x.shape[0]):
        x.iloc[i, 0] = f"**{x.iloc[i, 0]}**"
        #f"data-v1.html#{battery}/{x.iloc[i, 0]}"
        if i > 0 and x.iloc[i, 0] == x.iloc[lasti, 0]:
            x.iloc[i, 0] = ""
            x.iloc[i, 1] = ""
            x.iloc[i, 2] = ""
            idx[i] = ""
        else:
            idx[i] = j
            lasti = i
            j += 1
    x.index = idx
    print(x.to_markdown(index=True))
```


(sec:suite-v1)=
# Benchmark Suite (v`r VERSION`)

We have compiled **a large suite of benchmark datasets**.
For reproducibility, the datasets and label vectors are **versioned**.


Version `r VERSION` of the
[*Benchmark Suite for Clustering Algorithms*](https://github.com/gagolews/clustering-data-v1)
consists of **nine benchmark batteries**.
The five recommended ones:

1. {ref}`sec:battery-wut` 🌟,
2. {ref}`sec:battery-sipu` 🌟,
3. {ref}`sec:battery-fcps` 🌟,
4. {ref}`sec:battery-graves` 🌟,
5. {ref}`sec:battery-other` 🌟,

and four additional ones:

6. {ref}`sec:battery-uci`,
7. {ref}`sec:battery-mnist`,
8. {ref}`sec:battery-g2mg`,
9. {ref}`sec:battery-h2mg`.

Each battery consists of **several datasets of different origins**.
When referring to particular datasets, we use the convention
"`battery/dataset`", e.g, "{ref}`sec:battery-wut``/x2`".
Each dataset represents *n* points in $\mathbb{R}^d$
and is accompanied by at least one reference partition of cardinality *k*
(see below for a listing).


::::{important}
The versioned **snapshots of the suite** are available for download at:
<https://github.com/gagolews/clustering-data-v1/releases/tag/v`r VERSION`>.

All files can be browsed at:
<https://github.com/gagolews/clustering-data-v1/tree/v`r VERSION`>.

The **datasets** and the corresponding ground truth labels
can be browsed in the {ref}`sec:data-v1` section.

**Results** of different clustering algorithms can be investigated in the
{ref}`sec:results-v1` section.

See <https://genieclust.gagolewski.com/> and {cite}`aaa,cvi`
for example studies featuring different versions of this suite.
::::


<!--
Particular files can be https://github.com/gagolews/clustering-data-v1/raw/v`r VERSION`/wut/x2.txt
-->


The datasets are provided **solely for research purposes**,
unless stated otherwise.
As mentioned in the {ref}`sec:file-format` section,
each dataset is accompanied by a text file specifying more details thereon
(e.g., the literature references that we are asked to cite).


As a courtesy, **please cite** the current project
{cite}`clustering_benchmarks` as well as mention {cite}`clustering_data_v1`
which gives the exact version and URL of the dataset suite. Thank you.


There is some inherent overlap between the original databases.
We have tried to resolve any conflicts in the *best* possible manner.
Some datasets are equipped with
{ref}`additional reference labellings <sec:many-partitions>`
that did not appear in the original setting.








(sec:battery-wut)=
## `wut`

22 datasets in $\mathbb{R}^2$ or $\mathbb{R}^3$
authored by the fantastic students of Marek's 2016/2017 courses on Data Analysis
in R and [Python](https://datawranglingpy.gagolewski.com) at the
[Faculty of Mathematics and Information Science](https://www.pw.edu.pl/engpw/Academics/Faculties/Faculty-of-Mathematics-and-Information-Science), Warsaw University of Technology:
Anna Gierlak,
Eliza Kaczorek,
Mateusz Kobyłka,
Przemysław Kosewski,
Jędrzej Krauze,
Michał Maciąg,
Aleksander Truszczyński,
and
Adam Wawrzeńczyk.
Thanks!

```{python echo=FALSE,results="asis"}
summarise_battery("wut")
```




(sec:battery-sipu)=
## `sipu`

An excellent battery of 20 diverse datasets created/compiled/maintained
by P. Fränti and his colleagues and research students
from the University of Eastern Finland.
Available for download from <https://cs.joensuu.fi/sipu/datasets/>;
see {cite}`kmsix` for discussion:

* `a1`, `a2`, `a3`       {cite}`KarkkainenFranti2002:asets`,
* `aggregation`          {cite}`GionisETAL2007:clustagg`,
* `birch1`, `birch2`     {cite}`ZhangETAL1997:birch`,
* `compound`             {cite}`Zahn1971:gestalt`,
* `d31`, `r15`           {cite}`VeenmanETAL2002:maxvar`,
* `flame`                {cite}`FuMedico2005:flame`,
* `jain`                 {cite}`JainLaw2005:dilemma`,
* `pathbased`, `spiral`  {cite}`ChangYeung2008:pathbased`,
* `s1`, `s2`, `s3`, `s4` {cite}`FrantiVirmajoki2006:ssets`,
* `unbalance`            {cite}`psi`,
* `worms_2`, `worms_64`  {cite}`SieranojaFranti2019:densitypeaks`.


We have not included the `G2` sets as we suggest
the cluster variances should be corrected for space dimensionality;
see {ref}`sec:battery-g2mg` for an alternative.
`Birch3` is not included as no ground-truth labels were provided.
We excluded the `DIM`-sets as they are too easy for most algorithms.


```{python echo=FALSE,results="asis"}
summarise_battery("sipu")
```


(sec:battery-fcps)=
## `fcps`

9 datasets from the *Fundamental Clustering Problem Suite*
proposed by A. Ultsch {cite}`fcps` from the Marburg University,
Germany.

Each dataset consists of 212–4096 observations in 2–3 dimensions.
The `GolfBall` dataset is not included as it has no cluster structure.
`Tetragonula` and `Leukemia` are also not part of our suite
as they are given as distance matrices.

Data were originally available from elsewhere, but now
can be accessed, e.g., via the R package
[*FCPS*](https://CRAN.R-project.org/package=FCPS);
see also {cite}`ThrunUltsch2020:fcps`.

```{python echo=FALSE,results="asis"}
summarise_battery("fcps")
```





(sec:battery-graves)=
## `graves`

10 *synthetic data sets* discussed by D. Graves and W. Pedrycz
in {cite}`graves`.

Each dataset consists of 200–1050 observations in 2 dimensions.
Originally, they come with no reference labels.

```{python echo=FALSE,results="asis"}
summarise_battery("graves")
```





(sec:battery-other)=
## `other`

Datasets from multiple sources:

*   `chameleon_t4_8k`, `chameleon_t5_8k`, `chameleon_t7_10k`,
    `chameleon_t8_8k` – datasets supposedly related to the
    CHAMELEON algorithm by G. Karypis et al. {cite}`chameleon`.

    Source: <http://glaros.dtc.umn.edu/gkhome/cluto/cluto/download>

    In fact, in {cite}`chameleon` only two of the above
    (and some other ones) datasets are studied:
    `chameleon_t7_10k` is referred to as `DS3`,
    whilst `chameleon_t8_8k` is nicknamed `DS4`.
    The `DS2` set mentioned therein looks like a more noisy version
    of `fcps/twodiamonds`.

    <!--
    `chameleon_t4_8k` comes from the
    [SIPU](https://cs.joensuu.fi/sipu/datasets/) website;
    still, its screenshot does not appear in the aforementioned paper.
    -->

*   `hdbscan` – a dataset used for demonstrating the outputs of the
    [*hdbscan*](https://github.com/scikit-learn-contrib/hdbscan)
    package for Python {cite}`hdbscanpkg`;

* `iris`, `iris5` - "the" (see {cite}`bezdek_iris` for discussion)
    famous Iris {cite}`Fisher1936:iris` dataset
    and its imbalanced version considered in {cite}`genieins`;

* `square` – a dataset of unknown/unconfirmed origin
    (🚧 help needed 🚧).

```{python echo=FALSE,results="asis"}
summarise_battery("other")
```




(sec:battery-uci)=
## `uci`

A selection of 8 high-dimensional datasets available at the UCI
(University of California, Irvine)
[Machine Learning Repository](http://archive.ics.uci.edu/ml/)
{cite}`uci`.
Some of them were considered for benchmark purposes
in, amongst others, {cite}`graves`.
They are also listed in the {ref}`sec:battery-sipu` battery.
However, their original purpose is for testing classification,
not clustering algorithms.

```{python echo=FALSE,results="asis"}
summarise_battery("uci")
```




(sec:battery-mnist)=
## `mnist`

This battery features two large, high-dimensional datasets:

1. [MNIST](https://en.wikipedia.org/wiki/MNIST_database) –
    a database of handwritten digits (a preprocessed remix of
    [NIST](https://www.nist.gov/srd/nist-special-database-19) data
    made by Y. LeCun, C. Cortes, and C.J.C. Burges),

2. [Fashion-MNIST](https://github.com/zalandoresearch/fashion-mnist) –
    a similarly-structured dataset of Zalando articles
    compiled by H. Xiao, K. Rasul, and R. Vollgraf;
    see {cite}`fashion_mnist`.

Both datasets consist of 70,000 flattened 28x28 grayscale images
(train and test samples combined).

```{python echo=FALSE,results="asis"}
summarise_battery("mnist")
```



(sec:battery-g2mg)=
## `g2mg`

Each dataset consists of 2,048 observations from
two equisized Gaussian clusters in $d=1, 2, \dots, 128$ dimensions
(the components are sampled independently from a normal distribution).

They can be considered a modified version of Gaussian `G2`-sets from
<https://cs.joensuu.fi/sipu/datasets/>, but with variances
dependent on datasets' dimensionalities, i.e., $s\sqrt{d/2}$
for different *s*. This makes these new problems more difficult than
their original counterparts.
The 1-dimensional datasets as well as those of very low and very
high variances should probably be discarded.

It is well-known that such a data distribution
(multivariate normal with independent components)
is subject to the so-called curse of dimensionality,
leading to some weird behaviour for high *d*;
see, e.g., the Gaussian Annulus Theorem mentioned in {cite}`foundds`.

Generator: <https://github.com/gagolews/clustering-data-v1/blob/master/.devel/generate_gKmg.py>

We suggest that these datasets should be studied separately
from other batteries, because they are too plentiful.
Also, *parametric* algorithms that *specialise* in detecting
Gaussian blobs (*k*-means, expectation-maximisation (EM)
for Gaussian mixtures) will naturally perform better thereon than
the non-parametric approaches.

```{python echo=FALSE,results="asis"}
summarise_battery("g2mg")
```




(sec:battery-h2mg)=
## `h2mg`

Two Gaussian-like hubs of equal sizes,
with spread dependent on datasets' dimensionalities.
Each dataset consists of 2,048 observations in 1, 2, ..., 128 dimensions.
Each point is sampled from a sphere centred at its own cluster's centre,
of radius that follows the Gaussian distribution
with a predefined scaling parameter.

Generator: <https://github.com/gagolews/clustering-data-v1/blob/master/.devel/generate_hKmg.py>

Just like in the case of {ref}`sec:battery-g2mg`, we suggest
that these datasets should be studied separately from other batteries.

```{python echo=FALSE,results="asis"}
summarise_battery("h2mg")
```
