name: wheels

on: workflow_dispatch

env:
    # nmslib does not build on 32bit Windows
    # https://cibuildwheel.readthedocs.io/en/stable/options/
    # cp39-win_amd64
    # cp37-win32 cp38-win32 cp39-win32
    # scipy not yet available for cp311*
    CIBW_SKIP: cp2* pp* cp35* cp36* cp310-win32 cp311-win32 cp310-manylinux_i686 cp311-manylinux_i686 *-musllinux* cp311*
    CIBW_BEFORE_BUILD: pip install -r requirements.txt --upgrade

#[ubuntu-latest, windows-latest, macos-latest]
#https://github.com/pypa/cibuildwheel

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macOS-11, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.10.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
