name: genieclust for Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install libcurl4-openssl-dev python3-rpy2 libmlpack-dev r-base-dev python3-dev pandoc
        sudo python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then sudo pip3 install -r requirements.txt --upgrade; fi
        sudo pip3 install flake8 pytest --upgrade
    - name: Test and check Python
      run: |
        sudo make test
        sudo make check
